In [1]:
import numpy as np
import pandas as pd

In [2]:
arr1 = np.array([1,2,3,4])
np.transpose(arr1)

array([1, 2, 3, 4])

In [3]:
arr2 = np.array([[1,2,3],[4,5,6]])
np.transpose(arr2)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [4]:
ser1 = pd.Series([1,2,3,4])
ser1,ser1.shape

(0    1
 1    2
 2    3
 3    4
 dtype: int64,
 (4,))

In [5]:
np.transpose(ser1)

0    1
1    2
2    3
3    4
dtype: int64

In [6]:
df = pd.DataFrame([[1,2,3],[4,5,6]])
df

0  1  2
0  1  2  3
1  4  5  6

In [7]:
np.transpose(df)

0  1
0  1  4
1  2  5
2  3  6

In [8]:
ar1 = np.array([[1,2,3],[3,4,4],[5,6,6]])
ar2 = np.array([1,2,3])
(ar2.T).shape,ar2,ar1.shape,np.dot(ar1,ar2),np.dot(ar2,ar1)

((3,), array([1, 2, 3]), (3, 3), array([14, 23, 35]), array([22, 28, 29]))

In [9]:
ar3 = np.array([[1,2,3],[3,4,4],[5,6,6]])
ar4 = np.array([[1],[2],[3]])
np.dot(ar3,ar4),ar4.shape

(array([[14],
        [23],
        [35]]),
 (3, 1))

In [10]:
a1=np.array([[1,2,3],[4,5,6]])
a2 = np.array([1,2,3])
np.dot(a2,a1)

ValueError: shapes (3,) and (2,3) not aligned: 3 (dim 0) != 2 (dim 0)

In [14]:
a = np.array([1,2,3,4])
a=a.reshape(1,len(a))
a

array([[1, 2, 3, 4]])